<?php

return [

    'courses' => [
        'Certified Cloud Computing Professional',
        'Certified Cyber Security and Ethical Hacking Professional',
        'Certified Data Scientist',
        'Certified Database Administrator',
        'Certified Digital Marketing Professional',
        'Certified E-Commerce Professional',
        'Certified Graphic Designer',
        'Certified Java Developer',
        'Certified Mobile Application Developer',
        'Certified Python Developer',
        'Certified Social Media Manager',
        'Certified Web Developer',
    ],

    'districts' => [
        'badin' => 'Badin',
        'dadu' => 'Dadu',
        'ghotki' => 'Ghotki',
        'hyderabad' => 'Hyderabad',
        'jacobabad' => 'Jacobabad',
        'jamshoro' => 'Jamshoro',
        'karachi-central' => 'Karachi Central',
        'karachi-east' => 'Karachi East',
        'karachi-south' => 'Karachi South',
        'karachi-west' => 'Karachi West',
        'kashmore' => 'Kashmore',
        'khairpur' => 'Khairpur',
        'larkana' => 'Larkana',
        'matiari' => 'Matiari',
        'mirpurkhas' => 'Mirpurkhas',
        'naushahro-feroze' => 'Naushahro Feroze',
        'shaheed-benazirabad' => 'Shaheed Benazirabad',
        'qambar-shahdadkot' => 'Qambar Shahdadkot',
        'sanghar' => 'Sanghar',
        'shikarpur' => 'Shikarpur',
        'sukkur' => 'Sukkur',
        'tando-allahyar' => 'Tando Allahyar',
        'tando-muhammad-khan' => 'Tando Muhammad Khan',
        'tharparkar' => 'Tharparkar',
        'thatta' => 'Thatta',
        'umerkot' => 'Umerkot',
        'sujawal' => 'Sujawal',
        'korangi' => 'Korangi',
        'malir' => 'Malir',
    ],

    'study_centers' => [
        'MUET Jamshoro' => 'MUET, Jamshoro',
        'Hyderabad' => 'Hyderabad',
        'Mirpurkhas' => 'Mirpurkhas',
        'Dadu' => 'Dadu',
        'Thatta' => 'Thatta',
        'Badin' => 'Badin',
        'Tando Muhammad khan' => 'Tando Muhammad khan',
        'Hala' => 'Hala',
        'Umerkot' => 'Umerkot',
    ],
    'qualifications' => [
        'matric' => 'Matric',
        'intermediate' => 'Intermediate',
        'graduate' => 'Graduate',
    ],
    'genders' => [
        'male' => 'Male',
        'female' => 'Female',
        'transgender' => 'Transgender',
    ],

    'd_categories' => [
        'urban' => 'Urban',
        'rural' => 'Rural',
    ],
    'timeSlots' => [
        '9 AM to 12 PM' => '9 AM - 12 PM (Morning)',
        '12 PM to 3 PM' => '12 PM - 3 PM (Afternoon)',
        '3 PM to 6 PM' => '3 PM - 6 PM (Evening)',
        '6 PM to 9 PM' => '6 PM - 9 PM (Evening)',
        'Sat & Sun (Weekend)' => 'Sat & Sun (Weekend)',
    ],

];
