name: Build & Publish Deploy Branch
on:
  push:
    branches: [ master ]   # runs when you push to main OR master

env:
  APP_PATH: .   # app is at repo root

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Node deps
        working-directory: ${{ env.APP_PATH }}
        run: npm ci

      - name: Build assets (Vite)
        working-directory: ${{ env.APP_PATH }}
        run: npm run build

      - name: Show Vite output
        working-directory: ${{ env.APP_PATH }}
        run: |
          ls -la public || true
          ls -la public/build || true
          test -f public/build/manifest.json

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none

      - name: Install Composer deps (prod)
        working-directory: ${{ env.APP_PATH }}
        run: composer install --no-dev --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Prepare dist snapshot
        run: |
          set -e
          rsync -a "${APP_PATH}/" dist/ \
            --exclude ".git" --exclude ".github" --exclude "node_modules" \
            --exclude "tests" --exclude ".env*"
          test -f dist/public/build/manifest.json
          printf "%s\n" \
            ".env" \
            ".env.*" \
            "storage/logs" \
            "storage/framework/cache/data/*" \
            "storage/framework/sessions/*" \
            "storage/framework/views/*" > dist/.gitignore

      - name: Publish deploy branch
        run: |
          cd dist
          git init
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy from ${GITHUB_SHA}"
          git branch -M deploy
          git remote add origin "https://x-access-token:${{ secrets.DEPLOY_TOKEN }}@github.com/${{ github.repository }}.git"
          git push -f origin deploy
