- name: Publish deploy branch (fast-forward, no force)
  env:
    REPO_URL: https://x-access-token:${{ secrets.DEPLOY_TOKEN }}@github.com/${{ github.repository }}.git
    GIT_TRACE: "1"
    GIT_CURL_VERBOSE: "1"
  run: |
    set -euo pipefail
    set -x

    if git ls-remote --exit-code "$REPO_URL" deploy >/dev/null 2>&1; then
      git clone --depth=1 --branch=deploy "$REPO_URL" deploy-repo
    else
      git clone --depth=1 "$REPO_URL" deploy-repo
      cd deploy-repo
      git checkout --orphan deploy
      git rm -rf .
      git config user.name "github-actions"
      git config user.email "actions@github.com"
      git commit --allow-empty -m "Initialize deploy branch"
      git push -u origin deploy -v
      cd ..
    fi

    rsync -a --delete dist/ deploy-repo/

    cd deploy-repo
    git config user.name "github-actions"
    git config user.email "actions@github.com"
    git add -A

    if git diff --cached --quiet; then
      echo "No changes to deploy."
      exit 0
    fi

    git commit -m "Deploy from ${GITHUB_SHA}"
    git remote -v
    git log -1 --oneline
    git push -v origin deploy
